In [45]:
from pandas_datareader import data
import datetime
from bokeh.plotting import figure, show, output_file   

start=datetime.datetime(2021,3,12)
end=datetime.datetime(2021,4,1)

df=data.DataReader(name="GOOG",data_source="yahoo",start=start,end=end)
df

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2021-03-11,2125.699951,2072.379883,2074.060059,2114.770020,1238300,2114.770020
2021-03-12,2090.260010,2047.550049,2085.000000,2061.919922,1725000,2061.919922
2021-03-15,2067.060059,2043.510010,2062.300049,2066.489990,1298100,2066.489990
2021-03-16,2123.560059,2070.000000,2078.989990,2092.520020,1490600,2092.520020
2021-03-17,2109.780029,2054.000000,2076.030029,2091.080078,1297500,2091.080078
2021-03-18,2075.500000,2033.550049,2061.000000,2036.219971,1361400,2036.219971
2021-03-19,2053.100098,2017.680054,2042.050049,2043.199951,2314400,2043.199951
2021-03-22,2057.989990,2026.069946,2041.839966,2038.589966,1954800,2038.589966
2021-03-23,2072.302002,2039.219971,2051.699951,2052.959961,1367000,2052.959961
2021-03-24,2078.209961,2041.555054,2065.370117,2045.060059,1154000,2045.060059
2021-03-25,2058.870117,2010.729980,2044.810059,2044.359985,1418900,2044.359985
2021-03-26,2050.989990,2014.020020,2038.859985,2035.550049,1493500,2035.550049
2021-03-29,2058.429932,2015.619995,2027.880005,2055.949951,1229800,2055.949951
2021-03-30,2070.780029,2044.030029,2057.629883,2055.540039,1036600,2055.540039
2021-03-31,2093.326904,2056.745117,2059.120117,2068.629883,1459900,2068.629883
2021-04-01,2142.939941,2096.889893,2097.949951,2137.750000,1699000,2137.750000

In [46]:
###### Here define a function to devide the increase parts and decrease into two parts
###### function increase $ decrease = inc_dec
def inc_dec(c, o):
    if c > o:
        value="Increase"
    elif c < o:
        value="Decrease"
    else:
        value="Equal"
    return value

df["Status"]=[inc_dec(c,o) for c, o in zip(df.Close, df.Open)]

In [47]:
df["Middle"]=(df.Open+df.Close)/2
df["Height"]=abs(df.Close-df.Open)               #abs： makes sure that you will always get positive value

In [48]:
df

,High,Low,Open,Close,Volume,Adj Close,Status,Middle,Height
Date,,,,,,,,,
2021-03-11,2125.699951,2072.379883,2074.060059,2114.770020,1238300,2114.770020,Increase,2094.415039,40.709961
2021-03-12,2090.260010,2047.550049,2085.000000,2061.919922,1725000,2061.919922,Decrease,2073.459961,23.080078
2021-03-15,2067.060059,2043.510010,2062.300049,2066.489990,1298100,2066.489990,Increase,2064.395020,4.189941
2021-03-16,2123.560059,2070.000000,2078.989990,2092.520020,1490600,2092.520020,Increase,2085.755005,13.530029
2021-03-17,2109.780029,2054.000000,2076.030029,2091.080078,1297500,2091.080078,Increase,2083.555054,15.050049
2021-03-18,2075.500000,2033.550049,2061.000000,2036.219971,1361400,2036.219971,Decrease,2048.609985,24.780029
2021-03-19,2053.100098,2017.680054,2042.050049,2043.199951,2314400,2043.199951,Increase,2042.625000,1.149902
2021-03-22,2057.989990,2026.069946,2041.839966,2038.589966,1954800,2038.589966,Decrease,2040.214966,3.250000
2021-03-23,2072.302002,2039.219971,2051.699951,2052.959961,1367000,2052.959961,Increase,2052.329956,1.260010
2021-03-24,2078.209961,2041.555054,2065.370117,2045.060059,1154000,2045.060059,Decrease,2055.215088,20.310059
2021-03-25,2058.870117,2010.729980,2044.810059,2044.359985,1418900,2044.359985,Decrease,2044.585022,0.450073
2021-03-26,2050.989990,2014.020020,2038.859985,2035.550049,1493500,2035.550049,Decrease,2037.205017,3.309937
2021-03-29,2058.429932,2015.619995,2027.880005,2055.949951,1229800,2055.949951,Increase,2041.914978,28.069946
2021-03-30,2070.780029,2044.030029,2057.629883,2055.540039,1036600,2055.540039,Decrease,2056.584961,2.089844
2021-03-31,2093.326904,2056.745117,2059.120117,2068.629883,1459900,2068.629883,Increase,2063.875000,9.509766
2021-04-01,2142.939941,2096.889893,2097.949951,2137.750000,1699000,2137.750000,Increase,2117.849976,39.800049

In [49]:
p=figure(x_axis_type='datetime', width=1000, height=300)            #store the figure object in a p variable figure 
p.title="Candlestick Chart"

hours_12=12*60*60*1000
     
p.rect(df.index[df.Status=="Increase"], df.Middle[df.Status=="Increase"],                                        #定义单个方块图的左边位置，纵轴的中点是起始与结束时间的二分之一， 横轴位置以千分之一秒的刻度
       hours_12, df.Height[df.Status=="Increase"], fill_color="green", line_color="black")

p.rect(df.index[df.Status=="Decrease"], df.Middle[df.Status=="Decrease"],  
       hours_12, df.Height[df.Status=="Decrease"], fill_color="red", line_color="black")

output_file("CS.html")
show(p)